/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InfrastructureRouteImport } from './routes/infrastructure'
import { Route as HighlighterRouteImport } from './routes/highlighter'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ClipperRouteImport } from './routes/clipper'
import { Route as AutopilotRouteImport } from './routes/autopilot'
import { Route as IndexRouteImport } from './routes/index'

const InfrastructureRoute = InfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const HighlighterRoute = HighlighterRouteImport.update({
  id: '/highlighter',
  path: '/highlighter',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipperRoute = ClipperRouteImport.update({
  id: '/clipper',
  path: '/clipper',
  getParentRoute: () => rootRouteImport,
} as any)
const AutopilotRoute = AutopilotRouteImport.update({
  id: '/autopilot',
  path: '/autopilot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/autopilot': typeof AutopilotRoute
  '/clipper': typeof ClipperRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/highlighter': typeof HighlighterRoute
  '/infrastructure': typeof InfrastructureRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/autopilot': typeof AutopilotRoute
  '/clipper': typeof ClipperRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/highlighter': typeof HighlighterRoute
  '/infrastructure': typeof InfrastructureRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/autopilot': typeof AutopilotRoute
  '/clipper': typeof ClipperRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/highlighter': typeof HighlighterRoute
  '/infrastructure': typeof InfrastructureRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/autopilot'
    | '/clipper'
    | '/create'
    | '/dashboard'
    | '/highlighter'
    | '/infrastructure'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/autopilot'
    | '/clipper'
    | '/create'
    | '/dashboard'
    | '/highlighter'
    | '/infrastructure'
  id:
    | '__root__'
    | '/'
    | '/autopilot'
    | '/clipper'
    | '/create'
    | '/dashboard'
    | '/highlighter'
    | '/infrastructure'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutopilotRoute: typeof AutopilotRoute
  ClipperRoute: typeof ClipperRoute
  CreateRoute: typeof CreateRoute
  DashboardRoute: typeof DashboardRoute
  HighlighterRoute: typeof HighlighterRoute
  InfrastructureRoute: typeof InfrastructureRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/infrastructure': {
      id: '/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof InfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/highlighter': {
      id: '/highlighter'
      path: '/highlighter'
      fullPath: '/highlighter'
      preLoaderRoute: typeof HighlighterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clipper': {
      id: '/clipper'
      path: '/clipper'
      fullPath: '/clipper'
      preLoaderRoute: typeof ClipperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autopilot': {
      id: '/autopilot'
      path: '/autopilot'
      fullPath: '/autopilot'
      preLoaderRoute: typeof AutopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutopilotRoute: AutopilotRoute,
  ClipperRoute: ClipperRoute,
  CreateRoute: CreateRoute,
  DashboardRoute: DashboardRoute,
  HighlighterRoute: HighlighterRoute,
  InfrastructureRoute: InfrastructureRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
